### ISSUE TITLE
Need sudo before curl command

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/code-for-your-astro-pi-mission-space-lab-experiment#25]
There were 2 reports of this via the projects site feedback:

URL: /en/projects/code-for-your-astro-pi-mission-space-lab-experiment/2 With regards to any newcomer here: You should write sudo in front of the abovementioned curl comand. So that it says: sudo curl -sSL rpf.io/apstretch | bash

URL: /en/projects/code-for-your-astro-pi-mission-space-lab-experiment/2 correction: first 'sudo su' then 'curl -sSL rpf.io/apstretch | bash'

**Comment by martinohanlon** [comment]
Another comment re running the curl command URL: /en/projects/code-for-your-astro-pi-mission-space-lab-experiment/2 when we run the curl cmd it ends with the message that theres is no script to get.

**Comment by bennuttall** [comment]
When did this feedback come in? Astro Pi MSL closed a couple of months ago.

I can fix it but it's not relevant any more.

**Comment by bennuttall** [comment]
I don't see why it would need sudo

https://raw.githubusercontent.com/astro-pi/astro-pi-stretch-installer/master/setup.sh

**Comment by MarcScott** [comment]
This line would fail if they already had the repo I suppose.
`rm -rf astro-pi-stretch-installer`

Anyway - no harm in using sudo from what I can see

**Comment by bennuttall** [comment]
Ah, updated that.

Without sudo would be better, if only that it's fewer characters to type. Will revisit next time MSL is open.
