### ISSUE TITLE
missing hyperlinks

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/code-for-your-astro-pi-mission-space-lab-experiment#3]
While copy editing, I found a couple of places where it seems there should be hyperlinks:

Step 2, line 21: hyperlink to Teachers and mentors guide to coding for Phase 2 missing
Step 4, line 5: hyperlink to site with latest ISS TLE data missing?

**Comment by topshed** [comment]
thanks for spotting these - now added
