### ISSUE TITLE
Link leading to Not Found

### ISSUE THREAD

**Issue by KronwarsCZ** [raspberrypilearning/code-for-your-astro-pi-mission-space-lab-experiment#31]
After the part **Test your program** in **Introduction --> Additional information for educators**, you mention printer-friendly version of this project and include a link. That link leads to 404 Not found on projects.raspberry.org

**Comment by bennuttall** [comment]
Thanks! Have fixed this now - the correct link is https://projects.raspberrypi.org/en/projects/code-for-your-astro-pi-mission-space-lab-experiment/print
